package com.example.ecommerce.product.dto.request;

import com.example.ecommerce.product.entity.ProductStatus;
import com.example.ecommerce.product.entity.StockStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.util.List;

/**
 * Payload for creating or updating a product with complete information,
 * pricing, inventory, medicine specifications, media and SEO fields.
 */
@Schema(description = "Payload for creating or updating a product")
public class ProductRequest {

    // --- Product Information ---
    @NotBlank(message = "Product name is required")
    @Size(max = 150, message = "Product name must not exceed 150 characters")
    @Schema(description = "Product display name", example = "Paracetamol 500mg Tablets")
    private String name;

    @Size(max = 180, message = "Slug must not exceed 180 characters")
    @Pattern(regexp = "^[a-z0-9]+(?:-[a-z0-9]+)*$", message = "Slug must contain only lowercase alphanumeric characters and hyphens")
    @Schema(description = "Custom URL slug (autogenerated if blank)", example = "paracetamol-500mg-tablets")
    private String slug;

    @NotBlank(message = "Product SKU is required")
    @Size(max = 100, message = "SKU must not exceed 100 characters")
    @Schema(description = "Stock Keeping Unit SKU", example = "MED-PARA-500")
    private String sku;

    @Size(max = 100, message = "Barcode must not exceed 100 characters")
    @Schema(description = "UPC/EAN Barcode", example = "8901234567890")
    private String barcode;

    @Size(max = 150, message = "Generic name must not exceed 150 characters")
    @Schema(description = "Generic / INN name", example = "Paracetamol / Acetaminophen")
    private String genericName;

    @Size(max = 150, message = "Manufacturer name must not exceed 150 characters")
    @Schema(description = "Manufacturer name", example = "PharmaCare Labs")
    private String manufacturer;

    @Size(max = 500, message = "Short description must not exceed 500 characters")
    @Schema(description = "Short summary description", example = "Fast pain relief and fever reducer tablets.")
    private String shortDescription;

    @Schema(description = "Detailed HTML/Markdown long description")
    private String longDescription;

    // --- Relationships ---
    @Schema(description = "Associated Brand ID", example = "5")
    private Long brandId;

    @Schema(description = "Associated Category ID", example = "12")
    private Long categoryId;

    // --- Pricing ---
    @DecimalMin(value = "0.0", message = "Cost price must be non-negative")
    @Schema(description = "Cost price paid to supplier", example = "3.50")
    private BigDecimal costPrice;

    @NotNull(message = "Selling price is required")
    @DecimalMin(value = "0.0", message = "Selling price must be non-negative")
    @Schema(description = "Retail selling price", example = "5.99")
    private BigDecimal sellingPrice;

    @DecimalMin(value = "0.0", message = "Discount price must be non-negative")
    @Schema(description = "Promotional discount price", example = "4.99")
    private BigDecimal discountPrice;

    @DecimalMin(value = "0.0", message = "Discount percentage must be non-negative")
    @Schema(description = "Discount percentage", example = "16.69")
    private BigDecimal discountPercentage;

    @DecimalMin(value = "0.0", message = "Tax rate must be non-negative")
    @Schema(description = "Tax percentage", example = "5.00")
    private BigDecimal tax;

    @Size(max = 10, message = "Currency code must not exceed 10 characters")
    @Schema(description = "Currency code", example = "USD")
    private String currency;

    // --- Inventory ---
    @Min(value = 0, message = "Quantity must be non-negative")
    @Schema(description = "Total stock quantity", example = "150")
    private Integer quantity;

    @Min(value = 0, message = "Low stock threshold must be non-negative")
    @Schema(description = "Low stock alert threshold", example = "10")
    private Integer lowStock;

    @Min(value = 0, message = "Reserved quantity must be non-negative")
    @Schema(description = "Reserved stock quantity for pending orders", example = "5")
    private Integer reservedQuantity;

    @Schema(description = "Stock status", example = "IN_STOCK")
    private StockStatus stockStatus;

    // --- Media ---
    @Size(max = 500, message = "Thumbnail URL must not exceed 500 characters")
    @Schema(description = "Thumbnail image URL", example = "https://images.example.com/products/thumb-para.jpg")
    private String thumbnail;

    @Size(max = 500, message = "Video URL must not exceed 500 characters")
    @Schema(description = "Product demonstration video URL", example = "https://youtube.com/watch?v=123")
    private String videoUrl;

    @Valid
    @Schema(description = "Gallery image list")
    private List<ProductImageRequest> images;

    // --- Medicine Information ---
    @Schema(description = "Indicates whether prescription is required", example = "false")
    private Boolean prescriptionRequired;

    @Size(max = 100, message = "Dosage form must not exceed 100 characters")
    @Schema(description = "Dosage form", example = "Tablet")
    private String dosageForm;

    @Size(max = 100, message = "Strength must not exceed 100 characters")
    @Schema(description = "Active strength", example = "500mg")
    private String strength;

    @Size(max = 100, message = "Pack size must not exceed 100 characters")
    @Schema(description = "Pack size", example = "10x10 Blister Pack")
    private String packSize;

    @Size(max = 250, message = "Storage condition must not exceed 250 characters")
    @Schema(description = "Storage guidelines", example = "Store below 25°C in a dry place.")
    private String storageCondition;

    @Schema(description = "Safety warnings and precautions")
    private String warnings;

    @Schema(description = "Potential side effects")
    private String sideEffects;

    @Schema(description = "Active ingredients / composition")
    private String ingredients;

    // --- Product Flags ---
    @Schema(description = "Featured product flag", example = "true")
    private Boolean featured;

    @Schema(description = "Bestseller product flag", example = "true")
    private Boolean bestseller;

    @Schema(description = "New arrival flag", example = "false")
    private Boolean newArrival;

    @Schema(description = "Trending flag", example = "true")
    private Boolean trending;

    @Schema(description = "Recommended flag", example = "true")
    private Boolean recommended;

    // --- SEO ---
    @Size(max = 150, message = "Meta title must not exceed 150 characters")
    @Schema(description = "SEO meta title", example = "Buy Paracetamol 500mg Online")
    private String metaTitle;

    @Size(max = 500, message = "Meta description must not exceed 500 characters")
    @Schema(description = "SEO meta description", example = "Effective pain relief tablets with fast delivery.")
    private String metaDescription;

    @Size(max = 300, message = "Keywords must not exceed 300 characters")
    @Schema(description = "Search keywords", example = "paracetamol, pain relief, fever")
    private String keywords;

    // --- Status ---
    @Schema(description = "Product status", example = "ACTIVE")
    private ProductStatus status;

    @Schema(description = "Active flag", example = "true")
    private Boolean active;

    public ProductRequest() {
    }

    public ProductRequest(String name, String slug, String sku, String barcode, String genericName, String manufacturer,
                          String shortDescription, String longDescription, Long brandId, Long categoryId, BigDecimal costPrice,
                          BigDecimal sellingPrice, BigDecimal discountPrice, BigDecimal discountPercentage, BigDecimal tax,
                          String currency, Integer quantity, Integer lowStock, Integer reservedQuantity, StockStatus stockStatus,
                          String thumbnail, String videoUrl, List<ProductImageRequest> images, Boolean prescriptionRequired,
                          String dosageForm, String strength, String packSize, String storageCondition, String warnings,
                          String sideEffects, String ingredients, Boolean featured, Boolean bestseller, Boolean newArrival,
                          Boolean trending, Boolean recommended, String metaTitle, String metaDescription, String keywords,
                          ProductStatus status, Boolean active) {
        this.name = name;
        this.slug = slug;
        this.sku = sku;
        this.barcode = barcode;
        this.genericName = genericName;
        this.manufacturer = manufacturer;
        this.shortDescription = shortDescription;
        this.longDescription = longDescription;
        this.brandId = brandId;
        this.categoryId = categoryId;
        this.costPrice = costPrice;
        this.sellingPrice = sellingPrice;
        this.discountPrice = discountPrice;
        this.discountPercentage = discountPercentage;
        this.tax = tax;
        this.currency = currency;
        this.quantity = quantity;
        this.lowStock = lowStock;
        this.reservedQuantity = reservedQuantity;
        this.stockStatus = stockStatus;
        this.thumbnail = thumbnail;
        this.videoUrl = videoUrl;
        this.images = images;
        this.prescriptionRequired = prescriptionRequired;
        this.dosageForm = dosageForm;
        this.strength = strength;
        this.packSize = packSize;
        this.storageCondition = storageCondition;
        this.warnings = warnings;
        this.sideEffects = sideEffects;
        this.ingredients = ingredients;
        this.featured = featured;
        this.bestseller = bestseller;
        this.newArrival = newArrival;
        this.trending = trending;
        this.recommended = recommended;
        this.metaTitle = metaTitle;
        this.metaDescription = metaDescription;
        this.keywords = keywords;
        this.status = status;
        this.active = active;
    }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getSlug() { return slug; }
    public void setSlug(String slug) { this.slug = slug; }

    public String getSku() { return sku; }
    public void setSku(String sku) { this.sku = sku; }

    public String getBarcode() { return barcode; }
    public void setBarcode(String barcode) { this.barcode = barcode; }

    public String getGenericName() { return genericName; }
    public void setGenericName(String genericName) { this.genericName = genericName; }

    public String getManufacturer() { return manufacturer; }
    public void setManufacturer(String manufacturer) { this.manufacturer = manufacturer; }

    public String getShortDescription() { return shortDescription; }
    public void setShortDescription(String shortDescription) { this.shortDescription = shortDescription; }

    public String getLongDescription() { return longDescription; }
    public void setLongDescription(String longDescription) { this.longDescription = longDescription; }

    public Long getBrandId() { return brandId; }
    public void setBrandId(Long brandId) { this.brandId = brandId; }

    public Long getCategoryId() { return categoryId; }
    public void setCategoryId(Long categoryId) { this.categoryId = categoryId; }

    public BigDecimal getCostPrice() { return costPrice; }
    public void setCostPrice(BigDecimal costPrice) { this.costPrice = costPrice; }

    public BigDecimal getSellingPrice() { return sellingPrice; }
    public void setSellingPrice(BigDecimal sellingPrice) { this.sellingPrice = sellingPrice; }

    public BigDecimal getDiscountPrice() { return discountPrice; }
    public void setDiscountPrice(BigDecimal discountPrice) { this.discountPrice = discountPrice; }

    public BigDecimal getDiscountPercentage() { return discountPercentage; }
    public void setDiscountPercentage(BigDecimal discountPercentage) { this.discountPercentage = discountPercentage; }

    public BigDecimal getTax() { return tax; }
    public void setTax(BigDecimal tax) { this.tax = tax; }

    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }

    public Integer getQuantity() { return quantity; }
    public void setQuantity(Integer quantity) { this.quantity = quantity; }

    public Integer getLowStock() { return lowStock; }
    public void setLowStock(Integer lowStock) { this.lowStock = lowStock; }

    public Integer getReservedQuantity() { return reservedQuantity; }
    public void setReservedQuantity(Integer reservedQuantity) { this.reservedQuantity = reservedQuantity; }

    public StockStatus getStockStatus() { return stockStatus; }
    public void setStockStatus(StockStatus stockStatus) { this.stockStatus = stockStatus; }

    public String getThumbnail() { return thumbnail; }
    public void setThumbnail(String thumbnail) { this.thumbnail = thumbnail; }

    public String getVideoUrl() { return videoUrl; }
    public void setVideoUrl(String videoUrl) { this.videoUrl = videoUrl; }

    public List<ProductImageRequest> getImages() { return images; }
    public void setImages(List<ProductImageRequest> images) { this.images = images; }

    public Boolean getPrescriptionRequired() { return prescriptionRequired; }
    public void setPrescriptionRequired(Boolean prescriptionRequired) { this.prescriptionRequired = prescriptionRequired; }

    public String getDosageForm() { return dosageForm; }
    public void setDosageForm(String dosageForm) { this.dosageForm = dosageForm; }

    public String getStrength() { return strength; }
    public void setStrength(String strength) { this.strength = strength; }

    public String getPackSize() { return packSize; }
    public void setPackSize(String packSize) { this.packSize = packSize; }

    public String getStorageCondition() { return storageCondition; }
    public void setStorageCondition(String storageCondition) { this.storageCondition = storageCondition; }

    public String getWarnings() { return warnings; }
    public void setWarnings(String warnings) { this.warnings = warnings; }

    public String getSideEffects() { return sideEffects; }
    public void setSideEffects(String sideEffects) { this.sideEffects = sideEffects; }

    public String getIngredients() { return ingredients; }
    public void setIngredients(String ingredients) { this.ingredients = ingredients; }

    public Boolean getFeatured() { return featured; }
    public void setFeatured(Boolean featured) { this.featured = featured; }

    public Boolean getBestseller() { return bestseller; }
    public void setBestseller(Boolean bestseller) { this.bestseller = bestseller; }

    public Boolean getNewArrival() { return newArrival; }
    public void setNewArrival(Boolean newArrival) { this.newArrival = newArrival; }

    public Boolean getTrending() { return trending; }
    public void setTrending(Boolean trending) { this.trending = trending; }

    public Boolean getRecommended() { return recommended; }
    public void setRecommended(Boolean recommended) { this.recommended = recommended; }

    public String getMetaTitle() { return metaTitle; }
    public void setMetaTitle(String metaTitle) { this.metaTitle = metaTitle; }

    public String getMetaDescription() { return metaDescription; }
    public void setMetaDescription(String metaDescription) { this.metaDescription = metaDescription; }

    public String getKeywords() { return keywords; }
    public void setKeywords(String keywords) { this.keywords = keywords; }

    public ProductStatus getStatus() { return status; }
    public void setStatus(ProductStatus status) { this.status = status; }

    public Boolean getActive() { return active; }
    public void setActive(Boolean active) { this.active = active; }

    public static ProductRequestBuilder builder() { return new ProductRequestBuilder(); }

    public static class ProductRequestBuilder {
        private String name;
        private String slug;
        private String sku;
        private String barcode;
        private String genericName;
        private String manufacturer;
        private String shortDescription;
        private String longDescription;
        private Long brandId;
        private Long categoryId;
        private BigDecimal costPrice;
        private BigDecimal sellingPrice;
        private BigDecimal discountPrice;
        private BigDecimal discountPercentage;
        private BigDecimal tax;
        private String currency;
        private Integer quantity;
        private Integer lowStock;
        private Integer reservedQuantity;
        private StockStatus stockStatus;
        private String thumbnail;
        private String videoUrl;
        private List<ProductImageRequest> images;
        private Boolean prescriptionRequired;
        private String dosageForm;
        private String strength;
        private String packSize;
        private String storageCondition;
        private String warnings;
        private String sideEffects;
        private String ingredients;
        private Boolean featured;
        private Boolean bestseller;
        private Boolean newArrival;
        private Boolean trending;
        private Boolean recommended;
        private String metaTitle;
        private String metaDescription;
        private String keywords;
        private ProductStatus status;
        private Boolean active;

        ProductRequestBuilder() {}

        public ProductRequestBuilder name(String name) { this.name = name; return this; }
        public ProductRequestBuilder slug(String slug) { this.slug = slug; return this; }
        public ProductRequestBuilder sku(String sku) { this.sku = sku; return this; }
        public ProductRequestBuilder barcode(String barcode) { this.barcode = barcode; return this; }
        public ProductRequestBuilder genericName(String genericName) { this.genericName = genericName; return this; }
        public ProductRequestBuilder manufacturer(String manufacturer) { this.manufacturer = manufacturer; return this; }
        public ProductRequestBuilder shortDescription(String shortDescription) { this.shortDescription = shortDescription; return this; }
        public ProductRequestBuilder longDescription(String longDescription) { this.longDescription = longDescription; return this; }
        public ProductRequestBuilder brandId(Long brandId) { this.brandId = brandId; return this; }
        public ProductRequestBuilder categoryId(Long categoryId) { this.categoryId = categoryId; return this; }
        public ProductRequestBuilder costPrice(BigDecimal costPrice) { this.costPrice = costPrice; return this; }
        public ProductRequestBuilder sellingPrice(BigDecimal sellingPrice) { this.sellingPrice = sellingPrice; return this; }
        public ProductRequestBuilder discountPrice(BigDecimal discountPrice) { this.discountPrice = discountPrice; return this; }
        public ProductRequestBuilder discountPercentage(BigDecimal discountPercentage) { this.discountPercentage = discountPercentage; return this; }
        public ProductRequestBuilder tax(BigDecimal tax) { this.tax = tax; return this; }
        public ProductRequestBuilder currency(String currency) { this.currency = currency; return this; }
        public ProductRequestBuilder quantity(Integer quantity) { this.quantity = quantity; return this; }
        public ProductRequestBuilder lowStock(Integer lowStock) { this.lowStock = lowStock; return this; }
        public ProductRequestBuilder reservedQuantity(Integer reservedQuantity) { this.reservedQuantity = reservedQuantity; return this; }
        public ProductRequestBuilder stockStatus(StockStatus stockStatus) { this.stockStatus = stockStatus; return this; }
        public ProductRequestBuilder thumbnail(String thumbnail) { this.thumbnail = thumbnail; return this; }
        public ProductRequestBuilder videoUrl(String videoUrl) { this.videoUrl = videoUrl; return this; }
        public ProductRequestBuilder images(List<ProductImageRequest> images) { this.images = images; return this; }
        public ProductRequestBuilder prescriptionRequired(Boolean prescriptionRequired) { this.prescriptionRequired = prescriptionRequired; return this; }
        public ProductRequestBuilder dosageForm(String dosageForm) { this.dosageForm = dosageForm; return this; }
        public ProductRequestBuilder strength(String strength) { this.strength = strength; return this; }
        public ProductRequestBuilder packSize(String packSize) { this.packSize = packSize; return this; }
        public ProductRequestBuilder storageCondition(String storageCondition) { this.storageCondition = storageCondition; return this; }
        public ProductRequestBuilder warnings(String warnings) { this.warnings = warnings; return this; }
        public ProductRequestBuilder sideEffects(String sideEffects) { this.sideEffects = sideEffects; return this; }
        public ProductRequestBuilder ingredients(String ingredients) { this.ingredients = ingredients; return this; }
        public ProductRequestBuilder featured(Boolean featured) { this.featured = featured; return this; }
        public ProductRequestBuilder bestseller(Boolean bestseller) { this.bestseller = bestseller; return this; }
        public ProductRequestBuilder newArrival(Boolean newArrival) { this.newArrival = newArrival; return this; }
        public ProductRequestBuilder trending(Boolean trending) { this.trending = trending; return this; }
        public ProductRequestBuilder recommended(Boolean recommended) { this.recommended = recommended; return this; }
        public ProductRequestBuilder metaTitle(String metaTitle) { this.metaTitle = metaTitle; return this; }
        public ProductRequestBuilder metaDescription(String metaDescription) { this.metaDescription = metaDescription; return this; }
        public ProductRequestBuilder keywords(String keywords) { this.keywords = keywords; return this; }
        public ProductRequestBuilder status(ProductStatus status) { this.status = status; return this; }
        public ProductRequestBuilder active(Boolean active) { this.active = active; return this; }

        public ProductRequest build() {
            return new ProductRequest(name, slug, sku, barcode, genericName, manufacturer, shortDescription, longDescription, brandId, categoryId, costPrice, sellingPrice, discountPrice, discountPercentage, tax, currency, quantity, lowStock, reservedQuantity, stockStatus, thumbnail, videoUrl, images, prescriptionRequired, dosageForm, strength, packSize, storageCondition, warnings, sideEffects, ingredients, featured, bestseller, newArrival, trending, recommended, metaTitle, metaDescription, keywords, status, active);
        }
    }
}
