package com.example.ecommerce.brand.dto.request;

import com.example.ecommerce.brand.entity.BrandStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Request payload for creating or updating a brand.
 */
@Schema(description = "Payload for creating or updating a brand")
public class BrandRequest {

    @NotBlank(message = "Brand name is required")
    @Size(max = 100, message = "Brand name must not exceed 100 characters")
    @Schema(description = "Brand display name", example = "Apple")
    private String name;

    @Size(max = 120, message = "Slug must not exceed 120 characters")
    @Pattern(regexp = "^[a-z0-9]+(?:-[a-z0-9]+)*$", message = "Slug must contain only lowercase alphanumeric characters and hyphens")
    @Schema(description = "Custom URL slug (autogenerated if blank)", example = "apple")
    private String slug;

    @Size(max = 1000, message = "Description must not exceed 1000 characters")
    @Schema(description = "Brand description", example = "Global tech company designing premium consumer devices and software.")
    private String description;

    @Size(max = 500, message = "Logo URL must not exceed 500 characters")
    @Schema(description = "Brand logo image URL", example = "https://images.example.com/brands/apple-logo.png")
    private String logo;

    @Size(max = 500, message = "Banner image URL must not exceed 500 characters")
    @Schema(description = "Banner image URL", example = "https://images.example.com/brands/apple-banner.jpg")
    private String bannerImage;

    @Size(max = 300, message = "Website URL must not exceed 300 characters")
    @Pattern(regexp = "^(https?://)?([\\w.-]+)+[\\w/-]*$", message = "Invalid website URL format")
    @Schema(description = "Official website URL", example = "https://www.apple.com")
    private String websiteUrl;

    @Size(max = 100, message = "Country name must not exceed 100 characters")
    @Schema(description = "Country of origin", example = "United States")
    private String country;

    @Size(max = 150, message = "SEO title must not exceed 150 characters")
    @Schema(description = "SEO meta title", example = "Apple Official Store - Buy iPhones & MacBooks")
    private String seoTitle;

    @Size(max = 500, message = "SEO description must not exceed 500 characters")
    @Schema(description = "SEO meta description", example = "Shop official Apple devices, accessories, laptops and smartphones.")
    private String seoDescription;

    @Schema(description = "Brand operational status", example = "ACTIVE")
    private BrandStatus status;

    @Min(value = 0, message = "Sort order must be non-negative")
    @Schema(description = "Sort priority order", example = "5")
    private Integer sortOrder;

    @Schema(description = "Featured brand indicator", example = "true")
    private Boolean featured;

    @Schema(description = "Active indicator", example = "true")
    private Boolean active;

    public BrandRequest() {
    }

    public BrandRequest(String name, String slug, String description, String logo, String bannerImage, String websiteUrl,
                        String country, String seoTitle, String seoDescription, BrandStatus status, Integer sortOrder,
                        Boolean featured, Boolean active) {
        this.name = name;
        this.slug = slug;
        this.description = description;
        this.logo = logo;
        this.bannerImage = bannerImage;
        this.websiteUrl = websiteUrl;
        this.country = country;
        this.seoTitle = seoTitle;
        this.seoDescription = seoDescription;
        this.status = status;
        this.sortOrder = sortOrder;
        this.featured = featured;
        this.active = active;
    }

    public static BrandRequestBuilder builder() {
        return new BrandRequestBuilder();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getBannerImage() {
        return bannerImage;
    }

    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }

    public String getWebsiteUrl() {
        return websiteUrl;
    }

    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getSeoTitle() {
        return seoTitle;
    }

    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle;
    }

    public String getSeoDescription() {
        return seoDescription;
    }

    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription;
    }

    public BrandStatus getStatus() {
        return status;
    }

    public void setStatus(BrandStatus status) {
        this.status = status;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public static class BrandRequestBuilder {
        private String name;
        private String slug;
        private String description;
        private String logo;
        private String bannerImage;
        private String websiteUrl;
        private String country;
        private String seoTitle;
        private String seoDescription;
        private BrandStatus status;
        private Integer sortOrder;
        private Boolean featured;
        private Boolean active;

        BrandRequestBuilder() {
        }

        public BrandRequestBuilder name(String name) {
            this.name = name;
            return this;
        }

        public BrandRequestBuilder slug(String slug) {
            this.slug = slug;
            return this;
        }

        public BrandRequestBuilder description(String description) {
            this.description = description;
            return this;
        }

        public BrandRequestBuilder logo(String logo) {
            this.logo = logo;
            return this;
        }

        public BrandRequestBuilder bannerImage(String bannerImage) {
            this.bannerImage = bannerImage;
            return this;
        }

        public BrandRequestBuilder websiteUrl(String websiteUrl) {
            this.websiteUrl = websiteUrl;
            return this;
        }

        public BrandRequestBuilder country(String country) {
            this.country = country;
            return this;
        }

        public BrandRequestBuilder seoTitle(String seoTitle) {
            this.seoTitle = seoTitle;
            return this;
        }

        public BrandRequestBuilder seoDescription(String seoDescription) {
            this.seoDescription = seoDescription;
            return this;
        }

        public BrandRequestBuilder status(BrandStatus status) {
            this.status = status;
            return this;
        }

        public BrandRequestBuilder sortOrder(Integer sortOrder) {
            this.sortOrder = sortOrder;
            return this;
        }

        public BrandRequestBuilder featured(Boolean featured) {
            this.featured = featured;
            return this;
        }

        public BrandRequestBuilder active(Boolean active) {
            this.active = active;
            return this;
        }

        public BrandRequest build() {
            return new BrandRequest(name, slug, description, logo, bannerImage, websiteUrl, country, seoTitle, seoDescription, status, sortOrder, featured, active);
        }
    }
}
