services:
  - type: web
    name: ecommare-medi-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: "8080"
      - key: DB_URL
        value: jdbc:postgresql://dpg-da2a3ougekts73c5lm10-a:5432/ecommerce_db_qgb9
      - key: DB_USERNAME
        value: ecommerce_db_qgb9_user
      - key: DB_PASSWORD
        value: 7g1XT8fjX3SjaG63ShdHugwx99IZhj5U
      - key: JPA_DDL_AUTO
        value: update
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "https://pharma-care.puspo.online,https://ecommare-medi-frontend.vercel.app,http://localhost:3000"
      - key: REDIS_ENABLED
        value: "false"
      - key: STORAGE_BASE_URL
        value: ${RENDER_EXTERNAL_URL}
    healthCheckPath: /actuator/health
