services:
  - type: web
    name: pharmacare-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JPA_DDL_AUTO
        value: update
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://ecommare-medi-frontend.vercel.app,http://localhost:3000
      - key: REDIS_ENABLED
        value: "false"
      - key: STORAGE_BASE_URL
        value: ${RENDER_EXTERNAL_URL}
    healthCheckPath: /actuator/health
