package com.example.ecommerce.dashboard.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Top revenue-producing catalogue category breakdown.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Top category performance item")
public class TopCategoryResponse {

    @Schema(description = "Category ID", example = "12")
    private Long categoryId;

    @Schema(description = "Category Name", example = "Personal Care & Wellness")
    private String categoryName;

    @Schema(description = "Total orders containing products from category", example = "120")
    private Long orderCount;

    @Schema(description = "Total units sold in category", example = "420")
    private Long totalUnitsSold;

    @Schema(description = "Total revenue generated by category", example = "15420.00")
    private BigDecimal totalRevenue;

    @Schema(description = "Percentage share of overall store revenue", example = "28.5")
    private Double sharePercentage;

    @Schema(description = "Category thumbnail image URL", example = "https://cdn.example.com/cat/wellness.jpg")
    private String categoryImage;
}
