package com.example.ecommerce.dashboard.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Best-selling product entry ranking by quantity or total revenue generated.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Top selling product analytics item")
public class TopSellingProductResponse {

    @Schema(description = "Product ID", example = "105")
    private Long productId;

    @Schema(description = "Product Name", example = "Vitamin C 1000mg Effervescent")
    private String productName;

    @Schema(description = "Stock Keeping Unit (SKU)", example = "VIT-C-1000")
    private String sku;

    @Schema(description = "Category Name", example = "Supplements")
    private String categoryName;

    @Schema(description = "Total units sold during window", example = "350")
    private Long totalQuantitySold;

    @Schema(description = "Gross revenue generated by product", example = "8745.00")
    private BigDecimal totalRevenue;

    @Schema(description = "Thumbnail image URL", example = "https://cdn.example.com/products/vitc.jpg")
    private String thumbnail;
}
