package com.example.ecommerce.category.dto.request;

import com.example.ecommerce.category.entity.CategoryStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Request payload for creating or updating a product category.
 */
@Schema(description = "Payload for creating or updating a category")
public class CategoryRequest {

    @NotBlank(message = "Category name is required")
    @Size(max = 100, message = "Category name must not exceed 100 characters")
    @Schema(description = "Category display name", example = "Electronics & Accessories")
    private String name;

    @Size(max = 120, message = "Slug must not exceed 120 characters")
    @Pattern(regexp = "^[a-z0-9]+(?:-[a-z0-9]+)*$", message = "Slug must contain only lowercase alphanumeric characters and hyphens")
    @Schema(description = "Custom URL slug (autogenerated if blank)", example = "electronics-accessories")
    private String slug;

    @Size(max = 1000, message = "Description must not exceed 1000 characters")
    @Schema(description = "Category description", example = "High quality consumer electronics and mobile accessories")
    private String description;

    @Schema(description = "Parent category ID (null for root categories)", example = "12")
    private Long parentId;

    @Size(max = 500, message = "Category image URL must not exceed 500 characters")
    @Schema(description = "Category image URL", example = "https://images.example.com/categories/electronics.png")
    private String categoryImage;

    @Size(max = 500, message = "Banner image URL must not exceed 500 characters")
    @Schema(description = "Banner image URL for hero section", example = "https://images.example.com/banners/electronics-hero.jpg")
    private String bannerImage;

    @Size(max = 150, message = "SEO title must not exceed 150 characters")
    @Schema(description = "SEO meta title", example = "Buy Electronics & Accessories Online - Best Deals")
    private String seoTitle;

    @Size(max = 500, message = "SEO description must not exceed 500 characters")
    @Schema(description = "SEO meta description", example = "Explore top rated consumer electronics, smartphones and laptops with fast shipping.")
    private String seoDescription;

    @Schema(description = "Category operational status", example = "ACTIVE")
    private CategoryStatus status;

    @Min(value = 0, message = "Sort order must be non-negative")
    @Schema(description = "Sort priority order", example = "10")
    private Integer sortOrder;

    @Schema(description = "Mark category as featured on homepage/headers", example = "true")
    private Boolean featured;

    @Schema(description = "Active flag indicating availability", example = "true")
    private Boolean active;

    public CategoryRequest() {
    }

    public CategoryRequest(String name, String slug, String description, Long parentId, String categoryImage,
                           String bannerImage, String seoTitle, String seoDescription, CategoryStatus status,
                           Integer sortOrder, Boolean featured, Boolean active) {
        this.name = name;
        this.slug = slug;
        this.description = description;
        this.parentId = parentId;
        this.categoryImage = categoryImage;
        this.bannerImage = bannerImage;
        this.seoTitle = seoTitle;
        this.seoDescription = seoDescription;
        this.status = status;
        this.sortOrder = sortOrder;
        this.featured = featured;
        this.active = active;
    }

    public static CategoryRequestBuilder builder() {
        return new CategoryRequestBuilder();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getCategoryImage() {
        return categoryImage;
    }

    public void setCategoryImage(String categoryImage) {
        this.categoryImage = categoryImage;
    }

    public String getBannerImage() {
        return bannerImage;
    }

    public void setBannerImage(String bannerImage) {
        this.bannerImage = bannerImage;
    }

    public String getSeoTitle() {
        return seoTitle;
    }

    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle;
    }

    public String getSeoDescription() {
        return seoDescription;
    }

    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription;
    }

    public CategoryStatus getStatus() {
        return status;
    }

    public void setStatus(CategoryStatus status) {
        this.status = status;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public static class CategoryRequestBuilder {
        private String name;
        private String slug;
        private String description;
        private Long parentId;
        private String categoryImage;
        private String bannerImage;
        private String seoTitle;
        private String seoDescription;
        private CategoryStatus status;
        private Integer sortOrder;
        private Boolean featured;
        private Boolean active;

        CategoryRequestBuilder() {
        }

        public CategoryRequestBuilder name(String name) {
            this.name = name;
            return this;
        }

        public CategoryRequestBuilder slug(String slug) {
            this.slug = slug;
            return this;
        }

        public CategoryRequestBuilder description(String description) {
            this.description = description;
            return this;
        }

        public CategoryRequestBuilder parentId(Long parentId) {
            this.parentId = parentId;
            return this;
        }

        public CategoryRequestBuilder categoryImage(String categoryImage) {
            this.categoryImage = categoryImage;
            return this;
        }

        public CategoryRequestBuilder bannerImage(String bannerImage) {
            this.bannerImage = bannerImage;
            return this;
        }

        public CategoryRequestBuilder seoTitle(String seoTitle) {
            this.seoTitle = seoTitle;
            return this;
        }

        public CategoryRequestBuilder seoDescription(String seoDescription) {
            this.seoDescription = seoDescription;
            return this;
        }

        public CategoryRequestBuilder status(CategoryStatus status) {
            this.status = status;
            return this;
        }

        public CategoryRequestBuilder sortOrder(Integer sortOrder) {
            this.sortOrder = sortOrder;
            return this;
        }

        public CategoryRequestBuilder featured(Boolean featured) {
            this.featured = featured;
            return this;
        }

        public CategoryRequestBuilder active(Boolean active) {
            this.active = active;
            return this;
        }

        public CategoryRequest build() {
            return new CategoryRequest(name, slug, description, parentId, categoryImage, bannerImage, seoTitle, seoDescription, status, sortOrder, featured, active);
        }
    }
}
